name: Create new post

on:
  schedule:
    - cron: "30 * * * *"

jobs:
  execute-scraper:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.6"
      - run: go version

      - shell: bash
        run: |
          ./scrape-post.sh

      - uses: stefanzweifel/git-auto-commit-action@v4

      - shell: bash
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          cd server && ./deploy-server.sh

      - shell: bash
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_FROM_NUMBER: ${{ secrets.TWILIO_FROM_NUMBER }}
          TWILIO_TO_NUMBER: ${{ secrets.TWILIO_TO_NUMBER }}
        run: |
          cd twilio && ./send-notification.sh
