name: Create new post

on:
  schedule:
    - cron:  '30 * * * *'

jobs:
  execute-scraper:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.6'
      - run: go version

      - run: ./scraper.sh

      - uses: stefanzweifel/git-auto-commit-action@v4
