name: Create new post

on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:

jobs:
  execute-scraper:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.20.6"

      - run: go version

      - shell: bash
        run: |
          ./scripts/scrape-post.sh

      - uses: stefanzweifel/git-auto-commit-action@v4

      - name: "Deploy website"
        shell: bash
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          ./scripts/deploy-server.sh
